# House Price Prediction — Week 1 Internship Project

## Objective
The objective of this project is to build regression models that predict house prices using property-related features such as area, number of rooms, furnishing status, and other housing attributes.

## Tasks Covered
- Data loading
- Data exploration
- Missing value check
- Duplicate check
- Target and feature identification
- Initial data understanding

In [1]:
# Import required libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from pathlib import Path

# Display settings for better readability
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

In [2]:
# Define project paths

DATA_PATH = Path("data/Housing.csv")
CHARTS_PATH = Path("charts")

CHARTS_PATH.mkdir(exist_ok=True)

In [3]:
# Load the housing dataset

df = pd.read_csv(DATA_PATH)

print("Dataset loaded successfully.")

Dataset loaded successfully.

In [4]:
# Display first 10 rows of the dataset

df.head(10)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished

In [5]:
# Check number of rows and columns

rows, columns = df.shape

print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 545
Number of columns: 13

In [6]:
# Display all column names

df.columns.tolist()

['price',
 'area',
 'bedrooms',
 'bathrooms',
 'stories',
 'mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'parking',
 'prefarea',
 'furnishingstatus']

In [7]:
# Check data types and non-null values

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 69.2 KB

In [8]:
# Identify target and feature columns

target_column = "price"
feature_columns = [column for column in df.columns if column != target_column]

print(f"Target column: {target_column}")
print("Feature columns:")
for column in feature_columns:
    print(f"- {column}")

Target column: price
Feature columns:
- area
- bedrooms
- bathrooms
- stories
- mainroad
- guestroom
- basement
- hotwaterheating
- airconditioning
- parking
- prefarea
- furnishingstatus

In [9]:
# Check missing values in each column

missing_values = df.isnull().sum().sort_values(ascending=False)

missing_values

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [10]:
# Check duplicate rows

duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [11]:
# Summary statistics for numerical columns

df.describe()

              price          area    bedrooms   bathrooms     stories     parking
count  5.450000e+02    545.000000  545.000000  545.000000  545.000000  545.000000
mean   4.766729e+06   5150.541284    2.965138    1.286239    1.805505    0.693578
std    1.870440e+06   2170.141023    0.738064    0.502470    0.867492    0.861586
min    1.750000e+06   1650.000000    1.000000    1.000000    1.000000    0.000000
25%    3.430000e+06   3600.000000    2.000000    1.000000    1.000000    0.000000
50%    4.340000e+06   4600.000000    3.000000    1.000000    2.000000    0.000000
75%    5.740000e+06   6360.000000    3.000000    2.000000    2.000000    1.000000
max    1.330000e+07  16200.000000    6.000000    4.000000    4.000000    3.000000

In [12]:
# Identify categorical columns

categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()

print("Categorical columns:")
for column in categorical_columns:
    print(f"- {column}")

Categorical columns:
- mainroad
- guestroom
- basement
- hotwaterheating
- airconditioning
- prefarea
- furnishingstatus

C:\Users\ASUS\AppData\Local\Temp\ipykernel_18276\2139733323.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=["object"]).columns.tolist()

In [13]:
# Check unique values in categorical columns

for column in categorical_columns:
    print(f"\n{column}:")
    print(df[column].unique())

mainroad:
<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

guestroom:
<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

basement:
<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

hotwaterheating:
<ArrowStringArray>
['no', 'yes']
Length: 2, dtype: str

airconditioning:
<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

prefarea:
<ArrowStringArray>
['yes', 'no']
Length: 2, dtype: str

furnishingstatus:
<ArrowStringArray>
['furnished', 'semi-furnished', 'unfurnished']
Length: 3, dtype: str

## Day 1 Observations

- The dataset was successfully loaded using Pandas.
- The target column for prediction is `price`.
- All other columns are considered features for predicting house prices.
- Missing values and duplicate rows were checked.
- Categorical columns were identified for encoding in the next step.
- Further cleaning and preprocessing will be performed before model training.

## Data Quality Assessment

### Missing Values
The dataset contains no missing values across all columns.

### Duplicate Records
No duplicate records were found in the dataset.

### Data Types
The dataset contains both numerical and categorical features.

### Target Variable
The target variable for prediction is `price`.

### Data Readiness
The dataset is clean and suitable for preprocessing and machine learning model development.

# Task 2: Data Cleaning and Preprocessing

The dataset was inspected for missing values and duplicate records.

Since no missing values or duplicate rows were found, no rows were removed during the cleaning process.

The next step is to prepare categorical features for machine learning models.

In [15]:
# Create a copy of the dataset

housing_df = df.copy()

print("Working dataset created successfully.")

Working dataset created successfully.

In [16]:
# Verify missing values

missing_values = housing_df.isnull().sum()

print("Total missing values:")
print(missing_values.sum())

Total missing values:
0

In [17]:
# Verify duplicate rows

duplicate_count = housing_df.duplicated().sum()

print(f"Duplicate rows found: {duplicate_count}")

Duplicate rows found: 0

In [18]:
# Binary categorical columns

binary_columns = [
    "mainroad",
    "guestroom",
    "basement",
    "hotwaterheating",
    "airconditioning",
    "prefarea"
]

# Convert yes/no to 1/0

for column in binary_columns:
    housing_df[column] = housing_df[column].map({
        "yes": 1,
        "no": 0
    })

In [19]:
# Verify binary encoding

housing_df[binary_columns].head()

   mainroad  guestroom  basement  hotwaterheating  airconditioning  prefarea
0         1          0         0                0                1         1
1         1          0         0                0                1         0
2         1          0         1                0                0         1
3         1          0         1                0                1         1
4         1          1         1                0                1         0

In [20]:
# One-hot encode furnishing status

housing_df = pd.get_dummies(
    housing_df,
    columns=["furnishingstatus"],
    drop_first=True,
    dtype=int
)

In [21]:
# Display updated columns

housing_df.columns.tolist()

['price',
 'area',
 'bedrooms',
 'bathrooms',
 'stories',
 'mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'parking',
 'prefarea',
 'furnishingstatus_semi-furnished',
 'furnishingstatus_unfurnished']

In [22]:
# Dataset information after preprocessing

housing_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 14 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   price                            545 non-null    int64
 1   area                             545 non-null    int64
 2   bedrooms                         545 non-null    int64
 3   bathrooms                        545 non-null    int64
 4   stories                          545 non-null    int64
 5   mainroad                         545 non-null    int64
 6   guestroom                        545 non-null    int64
 7   basement                         545 non-null    int64
 8   hotwaterheating                  545 non-null    int64
 9   airconditioning                  545 non-null    int64
 10  parking                          545 non-null    int64
 11  prefarea                         545 non-null    int64
 12  furnishingstatus_semi-furnished  545 non-null    int64
 13  furnishingstatus_unfurnished     545 non-null    int64
dtypes: int64(14)
memory usage: 59.7 KB

In [23]:
# Define target variable

target_column = "price"

# Create feature matrix and target vector

X = housing_df.drop(columns=[target_column])

y = housing_df[target_column]

print(f"Feature matrix shape: {X.shape}")
print(f"Target vector shape: {y.shape}")

Feature matrix shape: (545, 13)
Target vector shape: (545,)

## Preprocessing Summary

The dataset required minimal cleaning because no missing values or duplicate records were present.

Binary categorical variables were converted from yes/no format into numerical values (1/0).

The furnishing status column was transformed using one-hot encoding to make it suitable for machine learning models.

The dataset is now fully prepared for model training and evaluation.

In [24]:
# Save processed dataset

housing_df.to_csv(
    "data/Housing_Cleaned.csv",
    index=False
)

print("Processed dataset saved successfully.")

Processed dataset saved successfully.